import "../styles/globals.css";
import Providers from "./Providers";
import { Badge } from "@/components/ui/badge";
import { createSSG } from "@/server/_app";
import SWRConfig from "./SWRConfig";
import { getNotifications } from "./fetchers";

export const metadata = {
	title: "tRPC-SWR App Directory",
	description: "Generated by Next.js",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const ssg = createSSG();
	return (
		<html lang="en">
			<body>
				<Providers>
					<header className="h-14 border-b flex items-center">
						<div className="container flex items-center gap-4">
							<h1 className="scroll-m-20 text-2xl font-semibold tracking-tight">
								tRPC-SWR
							</h1>
							<Badge variant="blue">App Dir</Badge>
						</div>
					</header>
					<SWRConfig
						value={{
							fallback: {
								[ssg.notifications.all.getKey()]: await getNotifications(),
							},
						}}
					>
						<main>{children}</main>
					</SWRConfig>
				</Providers>
			</body>
		</html>
	);
}
