import "@/styles/globals.css";
import Providers from "./Providers";

export const metadata = {
	title: "tRPC-SWR App Directory",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<Providers>
					<header className="h-14 border-b flex items-center">
						<div className="container">
							<h1 className="scroll-m-20 text-2xl font-semibold tracking-tight">
								{metadata.title}
							</h1>
						</div>
					</header>
					<main>{children}</main>
				</Providers>
			</body>
		</html>
	);
}
